import type { Config } from "tailwindcss";

const color = (property: string) => `rgb(var(${property}) / <alpha-value>)`;

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./content/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        ink: color("--color-ink"),
        "text-primary": color("--color-ink"),
        graphite: color("--color-graphite"),
        muted: color("--color-graphite"),
        "text-muted": color("--color-graphite"),
        line: color("--color-line"),
        "border-default": color("--color-line"),
        "border-active": color("--color-accent"),
        paper: color("--color-paper"),
        "surface-page": color("--color-paper"),
        "surface-card": color("--color-surface-card"),
        subtle: color("--color-subtle"),
        soft: color("--color-soft"),
        "surface-soft": color("--color-soft"),
        blush: color("--color-blush"),
        "accent-soft": color("--color-blush"),
        accent: color("--color-accent"),
        "accent-green": color("--color-accent"),
        "accent-technical": color("--color-accent"),
        "accent-readable": color("--color-accent-text"),
        terminal: color("--color-terminal"),
        pink: color("--color-pink"),
        "accent-cta": color("--color-pink"),
        "pink-dark": color("--color-pink-dark"),
        "cta-contrast-text": color("--color-cta-contrast-text"),
        focus: color("--color-focus"),
        "accent-muted": color("--color-accent-muted"),
        danger: color("--color-danger"),
        "case-section": color("--color-case-section"),
        "case-card": color("--color-case-card"),
        "case-panel": color("--color-case-panel"),
        "role-transport": color("--color-role-transport"),
        "role-transport-surface": color("--color-role-transport-surface"),
        "role-transform": color("--color-role-transform"),
        "role-transform-surface": color("--color-role-transform-surface"),
        "role-decide": color("--color-role-decide"),
        "role-decide-surface": color("--color-role-decide-surface"),
        "role-present": color("--color-role-present"),
        "role-present-surface": color("--color-role-present-surface"),
      },
      fontFamily: {
        sans: ["var(--font-family-sans)"],
        mono: ["var(--font-family-mono)"],
      },
      fontSize: {
        xs: ["0.875rem", { lineHeight: "1rem" }],
        sm: ["1rem", { lineHeight: "1.25rem" }],
        base: ["1.125rem", { lineHeight: "1.5rem" }],
        lg: ["1.25rem", { lineHeight: "1.75rem" }],
        xl: ["1.375rem", { lineHeight: "1.75rem" }],
        "2xl": ["1.625rem", { lineHeight: "2rem" }],
        "3xl": ["2rem", { lineHeight: "2.25rem" }],
        "4xl": ["2.375rem", { lineHeight: "2.5rem" }],
        "5xl": ["3.125rem", { lineHeight: "1" }],
        "6xl": ["3.875rem", { lineHeight: "1" }],
        "7xl": ["4.625rem", { lineHeight: "1" }],
        "technical-sm": "var(--font-size-technical-sm)",
        technical: "var(--font-size-technical)",
        "technical-lg": "var(--font-size-technical-lg)",
      },
      spacing: {
        "foundation-card": "var(--space-card)",
      },
      letterSpacing: {
        technical: "var(--tracking-technical)",
        "technical-wide": "var(--tracking-technical-wide)",
      },
      borderRadius: {
        "foundation-control": "var(--radius-control)",
        "foundation-card": "var(--radius-card)",
      },
      boxShadow: {
        "foundation-button": "var(--shadow-button-primary)",
        "foundation-card": "var(--shadow-card)",
        "foundation-card-technical": "var(--shadow-card-technical)",
        "foundation-card-cta": "var(--shadow-card-cta)",
        "foundation-highlight": "var(--shadow-highlight)",
        "foundation-flow": "var(--shadow-flow)",
        "foundation-investigation": "var(--shadow-investigation)",
      },
      transitionDuration: {
        foundation: "var(--motion-duration-base)",
      },
    },
  },
  plugins: [],
};

export default config;
